### ISSUE TITLE
[EPIC/PP4] OpenEmbedded (Yocto) Upstream

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1005]
Official Timeline: 2019.2Q

Backlogs:
- [x] Add "meta-neural-network" layer in OpenEmbedded
    - 1902A
- [x] Write working bitbake script for nnstreamer at https://github.com/nnsuite/meta-neural-network
- [ ] Write working bitbake script for tensorflow at https://github.com/nnsuite/meta-neural-network
- [ ] Write working bitbake script for tensorflow-lite at https://github.com/nnsuite/meta-neural-network
- [ ] Write working bitbake script for SSAT at https://github.com/nnsuite/meta-neural-network
- [ ] Write working bitbake script for protobuf at https://github.com/nnsuite/meta-neural-network
- [ ] Write working bitbake script for nnstreamer-ros at https://github.com/nnsuite/meta-neural-network
- [ ] Test OpenEmbedded Image loaded with NNStreamer.
    - After all related items are done, 1905B

**Comment by jijoongmoon** [comment]
I'm going to do this!

**Comment by wooksong** [comment]
@jijoongmoon I will catch up with you!

**Comment by myungjoo** [comment]
uh... done... for nnstreamer.
