### ISSUE TITLE
[EPIC/E1] ROS1 Support

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1059]
Timeline: 2019.1Q (Preferably completed in 1902A)

- [x] nnstreamer-ros / tensor_ros_sink #500
- [x] test cases for ros_sink https://github.com/nnsuite/nnstreamer/issues/1121
- [x] nnstreamer-ros / tensor_ros_src #503 #870
- [x] test cases for ros_src
- [x] packaging for nnstreamer-ros #956 #1037 #1085
- [x] releasing (launchpad & OBS) for nnstreamer-ros
- [ ] "app test" (ros node test) for ros_sink/src
- [x] CI integration
- [x] generating unit test coverage results and displaying them using CI
- [ ] writing brief README
