### ISSUE TITLE
[EPIC/UP1] Upstream to GStreamer.Freedesktop

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1061]
Timeline: 2019.4Q / Need continuous effort from 2019.1Q

Preliminary
- [ ] Ask them https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/950

Subtasks:
- [ ] Investigate their custom, rules, how-to. #948 
- [ ] Check if we can create "nnstreamer.git" in gstreamer.freedesktop.
- [ ] Check if we can do "pull-request" from nnstreamer.git to gst-plugins-*.git per directory basis, /gst/nnstreamer/*
- [ ] Merge the first element.
- [ ] Merge basic elements
- [ ] The whole elements in nnstreamer.git gets merged
- [ ] Find out upstreaming procedures for the predefined tensor_filter subplugins
- [ ] Find out upstreaming procedures for nnstreamer-ros.git (to ros.org? or to gstreamer.freedesktop?)

**Comment by myungjoo** [comment]
postponed indefinitely.
