### ISSUE TITLE
[EPIC PP7a] Tizen .tpk Custom Filter Support

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1139]
Background:
- Tizen security policy prohibits loading shared objects of application (dlopen/dlsym) from platform libraries or daemons.
- An application in .tpk may be packaged with its own neural network implemented as a custom filter.

The current worries:
- NNStreamer Tensor_Filter_Custom will NOT be able to load customfilter.so packaged in application.tpk

TODO (backlog)
- [x] Test how the platform reacts to customfilter.so of application.tpk
- [ ] Find a way to circumvent it.
- [ ] Implement the circumvent, test it.
- [ ] Release the circumvent to Tizen:Unified.
    - [ ] You may need to implement new / update C-API of custom filters.

Corresponding Timeline: This is to be done in 2019.3Q (for Tizen 5.5. M2 Release)

**Comment by kparichay** [comment]
- [X] Test how the platform reacts to customfilter.so of application.tpk

NNStreamer Tensor_Filter_Custom is able to read and load the custom_filter.so from application.tpk
Only requirement is for the custom_filter.so to have the correct elf format

**Comment by myungjoo** [comment]
Please list the RPM packages you've installed to the target device or emulator.

**Comment by kparichay** [comment]
The RPM packages (i686 version) installed on the target emulator - 

- nnstreamer
- nnstreamer-devel
- capi-nnstreamer
- capi-nnstreamer-devel

These packages are downloaded from http://download.tizen.org/snapshots/tizen/unified/latest/repos/emulator/packages/i686/

To install the package on emulator, 

- use `sdb root on` to get sudo permissions 
- `mount -o remount,rw \` 
- install using `rpm -i $PACKAGE.rpm`

This installation is only required if not using the latest tizen unified package. Using the latest tizen unified image in the emulator does not need any installations.
