### ISSUE TITLE
[EPIC] Tizen Sensor Framework as Input Source

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1143]
The output of Tizen sensor framework may become the input for nnstreamer pipeline.

- [x] Determine the rules of ouput format / usage pattern of TIzen sensor framework for nnstreamer
- [x] Determine the tensor types for Tizen sensor framework streams
- [x] Propose and determine the protocol draft with Tizen sensor framework team.
    - [x] Determine if this could be a subplugin of "tensor_source".
    - [x] Determine if this can be in nnstreamer.git/gst, nnstreamer.git/ext, or in another git repo.
- [x] Write the plugin, "tensor_TizenSensor_source"
- [x] Release!

**Comment by myungjoo** [comment]
To Be Determined:
- Include tensor_src_tizensensor in nnstreamer plugin **or** make it an independent plugin & subpackage (and locate at /ext/)

**Comment by myungjoo** [comment]
Done!
