### ISSUE TITLE
[NFR12] [Filter/Custom] Upgrade variable-dim (setInputDim) mode with intention advertising

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1181]
When a custom filter uses setInputDim (variable-dim) mode, tensor_filter assumes that the custom filter may accept arbitrary dimensions and types. However, this does not hold in many cases.

We need to let them optionally declare their intended ranges of input dimensions.

This can be started with (maybe we need to make this an EPIC and start with subissues)
- [ ] Allow to declare number of input tensors.
- [ ] Allow to declare range of number of input tensors.
- [ ] Allow to declare allowed types for input tensors.
- [ ] Allow to declare allowed # ranks for input tensors.
- [ ] Allow to declare allowed ranges of dimensiona of input tensors.

We will need to define a small, efficient, and highly-expressive language to declare such.

**Comment by myungjoo** [comment]
Scrap this. This is going to be way too complex and worthless.
