### ISSUE TITLE
[Epic: Performance] Support performance measurement facility

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#132]
**Issue by [geunsik-lim](https://github.sec.samsung.net/geunsik-lim)**
_Friday Jun 08, 2018 at 04:14 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/67_

----

## Background
We need to prepare a facility to measure performant of NNStreamer.  It can be combined to NNStreamer CI as an automated inspection tool to avoid performance deterioration, unexpted performance bottleneck, and so on.

## Action items:

*  Profiling - https://github.com/kirushyk/gst-instruments (by @sewon-oh ) #387 
   - [x] HawkTracer #855
   - [x] gst-instrument #864
*  Debugging - https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html  #340 
   - [x] GST_DEBUG #863
   - [x] GST_DEBUG_DUMP_DOT_DIR #752
   - [x] GStreamer Debugger (gst-debugger) #857
   - [x] [GStreamer debugging using GDB](https://developer.ridgerun.com/wiki/index.php/GStreamer_Debugging_Using_GDB)
*  Tracing - https://gstreamer.freedesktop.org/documentation/design/tracing.html
   - [x] GstShark #854
   - [x] [Pipeviz](https://github.com/virinext/pipeviz)
*  Aging test (code quality)
   - [x]  Runtest with fake Camera (v4l2loopback.ko)
   - [x] [gstreamer-ci](https://www.collabora.com/news-and-blog/blog/2018/06/11/gstreamer-ci-support-for-embedded-devices/) , NNStreamer uses TAOS-CI.
* Others
   - [x] [GstInterpipe](https://developer.ridgerun.com/wiki/index.php?title=GstInterpipe)
   - [ ] Debian Packaging (We assume that the default development PC is Ubuntu distribution.)
![image](https://user-images.githubusercontent.com/82404/45856158-555d8c80-bd8e-11e8-9432-38daac17822a.png)

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Friday Jun 08, 2018 at 04:14 GMT_

----

:octocat: **cibot**: Thank you for posting issue #67. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/geunsik-lim"><img src="https://github.sec.samsung.net/avatars/u/8170?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geunsik-lim](https://github.sec.samsung.net/geunsik-lim)**
_Thursday Jul 12, 2018 at 06:04 GMT_

----

# Case study: Tracing Gstreamer plugins

### Traces for buffer flow, events and messages in TRACE level:
GST_DEBUG="GST_TRACER:7,GST_BUFFER*:7,GST_EVENT:7,GST_MESSAGE:7"
GST_TRACERS=log gst-launch-1.0 fakesrc num-buffers=10 ! fakesink -
### Print some pipeline stats on exit:
GST_DEBUG="GST_TRACER:7" GST_TRACERS="stats;rusage"
GST_DEBUG_FILE=trace.log gst-launch-1.0 fakesrc num-buffers=10
sizetype=fixed ! queue ! fakesink && gst-stats-1.0 trace.log
### get ts, average-cpuload, current-cpuload, time and plot
GST_DEBUG="GST_TRACER:7" GST_TRACERS="stats;rusage"
GST_DEBUG_FILE=trace.log /usr/bin/gst-play-1.0 $HOME/Videos/movie.mp4 &&
./scripts/gst-plot-traces.sh --format=png | gnuplot eog trace.log.*.png
### print processing latencies
GST_DEBUG="GST_TRACER:7" GST_TRACERS=latency gst-launch-1.0 \
audiotestsrc num-buffers=10 ! audioconvert ! volume volume=0.7 ! \
autoaudiosink
### Raise a warning if a leak is detected
GST_TRACERS="leaks" gst-launch-1.0 videotestsrc num-buffers=10 !
fakesink
### check if any GstEvent or GstMessage is leaked and raise a warning
GST_DEBUG="GST_TRACER:7" GST_TRACERS="leaks(GstEvent,GstMessage)"
gst-launch-1.0 videotestsrc num-buffers=10 ! fakesink

### Performance
run ./tests/benchmarks/tracing.sh <tracer(s)> <media>

egrep -c "(proc|thread)-rusage" trace.log 658618 grep -c
"gst_tracer_log_trace" trace.log 823351

**Comment by leemgs** [comment]
* https://github.com/amzn/hawktracer (at 2018 Gstreamer Conference)
   * HawkTracer is a highly portable, low-overhead, configurable profiling tool built in Amazon Video for getting performance metrics from low-end devices.

Profiling GStreamer applications with HawkTracer and tracing subsystem. Marcin Kolny, Amazon

HawkTracer is lightweight and low-overhead profiler that allows to define custom trace events and provides infrastructure to create post-run and live data analyzers. In this talk, I'd like to demonstrate how can GStreamer applications be profiled and tuned in real time using HawkTracer, GStreamer Tracing subsystem and gst-debugger. I'll explain base concepts of HawkTracer, how to extend the profiler and how to integrate it to existing applications and GStreamer plugins(e.g. gst-shark tracing plugins) to get live profiling data.

Marcin is a software development engineer at Amazon. He spends his free time on contributing to several open source projects. For a few years he's been also a member of GNOME Foundation, where he maintains gstreamermm library and gst-debugger application, and contributes to a few other (mostly C++ related) projects.

Marcin's started using GStreamer framework couple of years ago in his previous job, where he was responsible for delivering video library for UAV system.

**Comment by myungjoo** [comment]
Let's try hawktracer+gst / gst-shark

**Comment by leemgs** [comment]
* https://github.com/RidgeRun/gst-shark

GstShark leverages GStreamers newest instrumentation subsystem by installing a set of custom hooks to the trace points. A variety of data analytics are extracted and presented to the user in a graphical, friendly way.

**Comment by leemgs** [comment]
> Let's try hawktracer+gst / gst-shark

The realted codes and manual will be added in ./tools/ folder.

**Comment by leemgs** [comment]
* Gstreamer Debugger (gst-debugger) : https://github.com/GNOME/gst-debugger/releases

**Comment by leemgs** [comment]
* Tracing result with gstshark:

![fig_tracing-02](https://user-images.githubusercontent.com/82404/50127163-4ca82400-02b3-11e9-907f-b13fd84c1802.PNG)
![fig_tracing-01](https://user-images.githubusercontent.com/82404/50127164-4d40ba80-02b3-11e9-9ed8-8d0707c73f37.PNG)
