### ISSUE TITLE
Flexible Input Dimension for Single-Shot API

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1651]
Support flexible input dimension for Single-Shot API, where user can adjust input size for each inference. This will not be supported for tensorflow-lite.

**Comment by myungjoo** [comment]
Note that flexible input dimension has become POSSIBLE by the new single-shot API implementation; the old implementation (gst-pipeline) cannot handle it. :)

**Comment by kparichay** [comment]
- [] Add setInOutDimension() callback for tensor filter plugins - sets input and output dimensions
- [] Support setInOutDimension()/setInputDimension() for various tensor filter subplugins which can support flexible input dimensions (setInputDimension() should do a sample run on zero tensor to get output tensor shape if cannot infer the shape from model directly)
  - [] Tensorflow
  - [] Pytorch
  - [] Caffe2
  - [] Tensorflow-lite - https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter#resizeinputtensor
  - [] python
- [] Add interface in nnstreamer.h to set flexible input+output dimension
- [] Add support for flexible input/output dimension in new single-c-api and not implemented for old version
- [] Add test cases

**Comment by myungjoo** [comment]
You don't need to support all frameworks from the start.
I'd recommend to do the whole steps with a single framework (TF or TF-Lite) and do the whole steps up to API test cases.

Then, later, expand the feature for other frameworks by extending internal-APIs (setInputOuputDim) and writing additional callbacks for them.

**Comment by kparichay** [comment]
Ok, then I will start with TF-lite, and extend it later.
