### ISSUE TITLE
Introduce to Coverity for OpenSource GitHub Repository

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#1682]
## Coverity
* Open-source
* Works with C, C++, C#, Objective-C, Java, JavaScript, node JS, Ruby, PHP and Python
* Supports 100 compilers
* Delivers a clear description of root causes of code issues
Vulnerabilities scanned for include resources leaks, NULL pointers, incorrect usage of APIs, use of uninitialized data, memory corruptions, buffer overruns, control flow, error handling, concurrency, insecure data, unsafe use of signed values and use of resources that have been freed
One of the best things about Coverity is that it finds the root cause of errors so you can easily make the changes needed. It also uses static analysis to find code defects, but the code under examination isn’t executed.

* Sign up here. https://scan.coverity.com/users/sign_up

## Proposal
![image](https://user-images.githubusercontent.com/82404/67254652-38c3e480-f4b9-11e9-9a9c-c51272b06ea3.png)

## coverity cloud for nnstreamer
* https://scan.coverity.com/projects/nnsuite-nnstreamer?tab=overview

![image](https://user-images.githubusercontent.com/82404/67254422-d9b1a000-f4b7-11e9-9df3-e3383111f66a.png)

## TAOS-CI: coverity module
![image](https://user-images.githubusercontent.com/82404/67254449-05cd2100-f4b8-11e9-90be-079bf8970c1d.png)

**Comment by leemgs** [comment]
## Register Your Open Source Project on Coverity Scan!!!
* https://scan.coverity.com/projects/nnsuite-nnstreamer/builds/new

**Comment by wooksong** [comment]
@leemgs I got the 'You are not authorized to access this page.' message. Do I need to do something else?

**Comment by myungjoo** [comment]
@wooksong I've sent you an invitation. Accept it. then you will get the access.

**Comment by leemgs** [comment]
Here is first step. 
https://github.com/nnsuite/nnstreamer/pull/1791

**Comment by leemgs** [comment]
## Action plan
The below items is an action list to interconnect between Coverity and nnstreamer repository.
- [ ] Understanding [Coverity script](http://mosaic.sec.samsung.net/kms/comty.do?comtyId=178669&menuId=2065405&postId=2065555&page=view&type=LIST) of SE department
- [ ] Analyze the operation structure of the Coverity
- [ ] Adding GitHub-based coverity serverce to nnstreamer repository
- [ ] Enabling the coverity service for nnstreamer repository
- [ ] Adding the new module for coverity (e.g., pr-prebuild-coverity )
- [ ] Enabling the coverity module of TAOS-CI for nnstreamer repository
- [ ] Adding the report file to help the contributors
- [ ] posting the report as a comment message whenever the Coverity module runs for PRs.

**Comment by leemgs** [comment]
## Error report
The coverity-scan generates two results as follows. We have to find a reason for this situation.

1. normal result:
```bash
OMISSION
```

2. inocrrect reulst:
```bash
[WARNING] No files were emitted. This may be due to a problem with your configuration
or because no files were actually compiled by your build command.
Please make sure you have configured the compilers actually used in the compilation.
 For more details, please look at:
    /var/www/ubuntu/nnstreamer/build/cov-int/build-log.txt
ubuntu@ip-172-31-27-164:~/nnstreamer/build$
```

**Comment by leemgs** [comment]
## Here is my prototype to evaluate Coverity module manually.

```bash
#!/usr/bin/env bash
# @author: Geunsik Lim <geunsik.lim@samsung.com> 

function coverity-build {
    # pull changes
    git pull

    # configure the compiler type and compiler command
    cov-configure --comptype prefix --compiler ccache
    cov-configure --comptype gcc --compiler cc
    cov-configure --comptype g++ --compiler c+

    # run cov-build command
    rm -rf build-coverity
    rm -rf cov-int
    meson build-coverity
    cov-build --dir cov-int ninja -C build-coverity
}

function coverity-commit {
    # configuration
    export TZ=Asia/Seoul
    _date=$(date '+%Y%m%d-%H%M')
    _description="${date}-coverity"
    _token="PxGfTFJGzXDh46FiTP6ZWQ"
    _email="leemgs@gmail.com"
    _coverity_site="https://scan.coverity.com/builds?project=nnsuite%2Fnnstreamer"

    # exception handling
    if [[ ! $1 ]]; then
        echo "Creating the tar file ..."
        _file="myproject-${_date}.tgz"
        tar cvzf ./$_file ./cov-int/
    else
        _file="$1"
    fi

    # commit the coverity execution result
    curl --form token=$_token \
      --form email=$_email \
      --form file=@$_file \
      --form version="$_date" \
      --form description="$_description" \
      $_coverity_site
    result=$?

    if [[ $result -eq 0 ]]; then
        echo -e "Congrats. The return value is $result. The all tasks are successfully completed."
    else
        echo -e "Ooops.... The return value is $result. The some tasks are unfortunately failed."
    fi
}

## main
coverity-build
coverity-commit
~

```

**Comment by leemgs** [comment]
### Monitoring a commit status at https://scan.coverity.com

* https://scan.coverity.com/projects/nnsuite-nnstreamer/builds/new?tab=upload


1. Nothing

2. 
Build Submission Temporarily Unavailable
Your build is already in the queue for analysis. Please wait till analysis finishes before uploading another build.


2.1 Last Build Status: Running. Your build is currently being analyzed
    (https://scan.coverity.com/projects/nnsuite-nnstreamer)

	
3. 
Build Submission Temporarily Unavailable
The build submission quota for this project has been reached. Next submission permitted on or after 2019-Oct-31  1:12 AM UTC

**Comment by myungjoo** [comment]
Done.
