### ISSUE TITLE
[EPIC/E6] tensor_load & tensor_save

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#388]
Official Timeline: 2019.3Q

Refer to gst/tensor_saveload/README.md after PR #321 

- [ ] Confirm & Add Typefind for other/tensorsave
    - Be ready for new future requirement (2020): compressed / N-bit tensorsave & tensor & tensors
- [ ] Write tensor_save
- [ ] Write tensor_load
- [ ] Test tensor_load & tensor_save

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 24, 2018 at 02:44 GMT_

----

:octocat: **cibot**: Thank you for posting issue #322. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Note: need to use BaseElement, not BaseTransform, because the metadata of tensor is retrieved after the pipeline has been configured and running. You cannot get the dimension information during PADCAP negotiations.

**Comment by myungjoo** [comment]
Looks like filesrc and filesink are enough for us. No one has complained it. :)
