### ISSUE TITLE
[Pipeviz] Crashes when pipeviz uses nnstreamer

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#700]
Somebody, anyone who's got free hands, please test a full nnstreamer stream (video->t-converter->t-filter->t-decoder->videosink) and fix related issues (crashes).

- [x] decoder cannot get-property in pipeviz to edit its properties #796
```
failed to get the current screen resources
QXcbConnection: XCB error: 170 (Unknown), sequence: 163, resource id: 90, major code: 146 (Unknown), minor code: 20
**
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_decoder/tensordec.c:774:gst_tensordec_get_property: assertion failed: (self->mode < DECODE_MODE_UNKNOWN)
Aborted (core dumped)
```
- [x] decoder cannot set-property in pipeviz: #798
```
mzx@kohaku:/source/AutoDrv/pipeviz$ ./pipeviz
failed to get the current screen resources
QXcbConnection: XCB error: 170 (Unknown), sequence: 163, resource id: 90, major code: 146 (Unknown), minor code: 20
**
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_decoder/tensordec.c:724:gst_tensordec_set_property: assertion failed: (key >= 0)
Aborted (core dumped)
```
- [x] videotestsrc->t_c->t_d->videoconvert->ximagesink FAIL #799
```
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_decoder/tensordec-directvideo.c:130:dv_decode: assertion failed: (gst_buffer_get_size (outbuf) == 0)
Aborted (core dumped)
```
- [x] Drawing t_c->t_f->t_d (direct_video) FAIL  #800
```
Thread 1 "pipeviz" received signal SIGSEGV, Segmentation fault.
0x00007fffe1aede0b in gst_tensor_filter_load_tensor_info (self=0xbae0d0) at /source/AutoDrv/NNStreamer/gst/tensor_filter/tensor_filter.c:770
770	    if (self->fw->getInputDimension) {
(gdb) 
```
- [x] video -> t_c -> t_f (1:1) -> t_d (direct_video) -> videoconvert -> ximagesink  #816 Fixed!
When model path is given to tensor_filter after configuring framework as custom
```
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_filter/tensor_filter.c:507:gst_tensor_filter_set_property: assertion failed: (prop->custom_properties == NULL && value)
```
(after applying workaround)
```
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_filter/tensor_filter.c:399:gst_tensor_filter_set_property: assertion failed: (prop->nnfw == _T_F_UNDEFINED && value)
```
(after yet another workaround)
```
Thread 1 "pipeviz" received signal SIGSEGV, Segmentation fault.
0x00007fffe038f9e3 in custom_loadlib (filter=0xfec0d0, private_data=0xfec310) at /source/AutoDrv/NNStreamer/gst/tensor_filter/tensor_filter_custom.c:78
78	      *((NNStreamer_custom_class **) dlsym (ptr->handle, "NNStreamer_custom"));
```
Then...
```
[New Thread 0x7fffe2068700 (LWP 28929)]
**
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_filter/tensor_filter.c:433:gst_tensor_filter_set_property: assertion failed: (prop->model_file == NULL && value)

```
After fixing them all with workarounds;;;
```
** (pipeviz:29391): WARNING **: /source/AutoDrv/NNStreamer/gst/tensor_filter/tensor_filter.c:1049 Cannot get the output tensor info.
**
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_filter/tensor_filter.c:1050:gst_tensor_filter_transform_caps: assertion failed: (0)

Thread 6 "videotestsrc0:s" received signal SIGABRT, Aborted.
```
- [x] [NOT TESTED] video -> tee X -> videoscale -> t_c -> t_f (label) -> t_d (label) -> textmixer (X) -> videoconvert -> ximagesink THE DEMO-1 / Need to Test

```
**
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_converter/tensor_converter.c:340:gst_tensor_converter_set_property: assertion failed: (self->tensor_info.type != _NNS_END)
```

**Comment by jinhyuck-park** [comment]
one of reason for this crash, as I tested before,
assertion fails when change property of element(ex tensor filter)
because, as of now, changing property on running time is prohibited in tensor filter.
gst launch and nnstreamer examples set properties before run-time
but when use pipeviz, first you have to choose element form elements list, at this time, elements set property as init property values, after that when user changes properties(ex tensorflow-lite model path),
it crashes with assertion in element's 'set property' function.

**Comment by myungjoo** [comment]
Done. and Pipeviz commits upstreamed.
