### ISSUE TITLE
[EPIC/NR5] Plug and Play Sub-Plugin Support

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#846]
SPRINT 1812A: Determine what are needed to be implemented, list up "issues".

- Requirements
    - All additional subplugins must be able to be built externally with "dev" packaging.
        - These are considered to be "API" set of NNSTREAMER.
        - They should have clear "scope" and device security should be considered.
        - Before releasing 0.1, these API must be fixed for future "backward compatibility".
        - We should consider providing language bindings
            - Required: C# (for Tizen), C++ (cause it's trivial), Java (for Android), Javascript (for Tizen)
            - Optionally considered: Rust (We need to be a bit accustomed to Rust for future GST)
    - All additional subplugins must be able to be executed as a separated binaries without rebuilding nnstreamer
    - Dev packaging should have minimal package dependencies
    - App/Pipeline developer using such additional subplugins should be able to install subplugins right before launching to use them.
    - Research how to make it official Tizen APIs or internal APIs.

- Corresponding elements
    - tensor_filter
    - tensor_decoder

# A. Run-time attachable filter/decoder/custom filters
- [ ] #761 Refactor filter::main for non-custom filters, online probing
- [ ] #786 tensor_filter subplugin register at runtime.
- [x] #935 tensor_decoder subplugin

# B. Deployment test (separated .so)
- [ ] #786 tensor_fitler subplugin deployed as .so

# C. Independently built filter/decoder/custom filters
- [ ] #1037 exported subplugin headers
- [ ] #786 tensor_fitler subplugin built externally

# Extended (not required for closing this EPIC)
- [ ] #764 Custom Filter Code Generator
