### ISSUE TITLE
[Example/MTCNN] Performance measurement on ODROID-XU4

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#902]
- [x] 1. Replace add-mul operator of tensor_transform:arithmetic with newly defined add,mul operators
  - @wooksong https://github.sec.samsung.net/STAR/nnstacker/pull/116
- [x] 2. Implement 'multifilesrc' mode, which uses image files instead of v4l2src as an input source
  - @wooksong https://github.sec.samsung.net/STAR/nnstacker/pull/119
- [x] 3. Implement neural network pipeline-only mode 
  - @again4you https://github.sec.samsung.net/STAR/nnstacker/pull/117
- [x] 4. Adjust the method for calculating each width and height of images that the image pyramid includes
  - @wooksong https://github.sec.samsung.net/STAR/nnstacker/pull/120 https://github.sec.samsung.net/STAR/nnstacker/pull/121
- [x] 5. Revise performance measurement feature
  - @again4you https://github.sec.samsung.net/STAR/nnstacker/pull/117
  - @wooksong https://github.sec.samsung.net/STAR/nnstacker/pull/129 https://github.sec.samsung.net/STAR/nnstacker/pull/123 https://github.sec.samsung.net/STAR/nnstacker/pull/124
- [x] 6. Revive the RPM spec files
  - @again4you https://github.sec.samsung.net/STAR/nnstacker/pull/122
- [x] 7. Measure the performance of MTCNN on Tizen/ODROID-XU4
  - @again4you https://github.sec.samsung.net/STAR/nnstacker/pull/127 

All implementations would be made available on the repositories of https://github.sec.samsung.net, not here.

**Comment by myungjoo** [comment]
Before closing this, please send a performance benchmark report (table).

**Comment by myungjoo** [comment]
Paper Submitted. Thank you everyone!
