### ISSUE TITLE
[EPIC/PP3] Android Platform Support & Project:NS

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#978]
Timeline: 2019.1Q

### Background

Currently, NNstreamer supports the two operating systems as following:
   * Ubuntu 16.04
   * Tizen 5.0

Now, It is an appropriate time to support Android software platform additionally for a NNstreamer proliferation. 

----
### Action items (for EPIC)
- [x] Understanding latest NDK & SDK of Android
   - [x] [Manual] https://developer.android.com/ndk/
   - [x] Checked a difference of Android features since 2014-08-30
- [x] Build C/C++ test applications of Gstreamer with NDK/JNI 
   - [MergeRequest] https://gitlab.freedesktop.org/gstreamer/cerbero/merge_requests/45
   - [Merged] https://gitlab.freedesktop.org/gstreamer/cerbero/commit/8727d56c92f5bd424fafa000d442730c3dc15bbc
- [x] Build Java test applications of Gstreamer with SDK/AndroidStudiod
   - [wiki] https://github.com/nnsuite/nnstreamer/wiki/%5BAndroid%5D-How-to-build-Android-applications-on-Ubuntu
- [x] Evaluate test application of Android/gstreamer on embedded board
   - [x] on Galaxy Note 5: Succeeded.
   - [x] on Raspberry Pi3:  Verified  https://github.com/nnsuite/nnstreamer/issues/978#issuecomment-451036845
- [x] Android/bionic: Building Gstreamer source using Cerbero on Ubuntu
   - https://gitlab.freedesktop.org/gstreamer/cerbero
   - https://gstreamer.freedesktop.org/data/pkg/android/ (Prebuilt binaries)
- [x] Android/bionic: Building NNstreamer source using Cerbero on Ubuntu
- [ ] Build C/C++ test applications of NNstreamer with SDK/AndroidStudio 
  - Android Sample GUI Application (issue #724)
- [ ] CI/CD: Support Android package builder to control PRs in real time
   - [ ] AWS/X86_64: Android build test: NNstreamer
      https://github.com/nnsuite/nnstreamer/issues/1165
   - [ ] AWS/ARM: Android runt test: example applications
- [ ] TBA (To Be Added)
   - TODO1
   - TODO2
- [x] Project:NS for Android @jijoongmoon 
    - [x] Get the H/W + S/W Platform
    - [x] Install GST
    - [x] Test basic GST examples
    - [x] Install NNStreamer plugins
    - [x] Test basic NNStreamer examples
    - [ ] Install all related packages
    - [ ] Test Project:NS pipelines
    - [ ] Release

### Documentation
- [ ] https://github.com/nnsuite/nnstreamer/wiki/%5BAndroid%5D-How-to-build-Android-applications-on-Ubuntu

**Comment by leemgs** [comment]
Oooops. We could not run Android emulator on AWS/X86_64 instance. 

* Screenshot:
![image](https://user-images.githubusercontent.com/82404/49839137-1f5e0080-fdf1-11e8-94ce-cb24913d5b81.png)

**Comment by leemgs** [comment]
* The package list that Cerbero requires to build gst-android prebuilt binaries.

```bash


ubuntu@ip-172-31-27-164:/var/www/gst-android/cerbero$ ls -al ~/.cache/cerbero-sources/
\ud569\uacc4 544356
drwxrwxr-x 92 ubuntu ubuntu      4096 12\uc6d4 13 01:48 .
drwx------ 14 ubuntu ubuntu      4096 12\uc6d4 13 00:13 ..
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:44 a52dec-0.7.4
-rw-rw-r--  1 ubuntu ubuntu 557038702 10\uc6d4 13 02:14 android-ndk-r18b-linux-x86_64.zip
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:14 autoconf-2.69
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:14 automake-1.15.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:34 bzip2-1.0.6
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:35 cairo-1.14.12
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:34 expat-2.2.5
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:45 ffmpeg-4.0.2
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:50 flac-1.3.2
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:35 fontconfig-2.12.6
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:34 freetype-2.9
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:36 fribidi-1.0.5
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:44 gdk-pixbuf-2.38.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:14 gettext-m4-0.19.8.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:15 gettext-tools-0.19.8.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:32 glib-2.56.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:48 glib-networking-2.56.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:28 glib-tools-2.56.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:45 gmp-6.1.2
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:46 gnutls-3.5.18
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:18 gobject-introspection-m4-1.54.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:42 graphene-1.8.2
drwxrwxr-x 15 ubuntu ubuntu      4096 12\uc6d4 13 01:48 gst-editing-services-1.0
drwxrwxr-x 11 ubuntu ubuntu      4096 12\uc6d4 13 01:47 gst-libav-1.0
drwxrwxr-x 15 ubuntu ubuntu      4096 12\uc6d4 13 01:44 gst-plugins-bad-1.0
drwxrwxr-x 16 ubuntu ubuntu      4096 12\uc6d4 13 00:43 gst-plugins-base-1.0
drwxrwxr-x 14 ubuntu ubuntu      4096 12\uc6d4 13 00:51 gst-plugins-good-1.0
drwxrwxr-x 13 ubuntu ubuntu      4096 12\uc6d4 13 01:45 gst-plugins-ugly-1.0
drwxrwxr-x  9 ubuntu ubuntu      4096 12\uc6d4 13 01:45 gst-rtsp-server-1.0
drwxrwxr-x 10 ubuntu ubuntu      4096 12\uc6d4 13 01:48 gst-validate
drwxrwxr-x 16 ubuntu ubuntu      4096 12\uc6d4 13 00:32 gstreamer-1.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:18 gtk-doc-lite-1.29
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:36 harfbuzz-1.7.5
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:18 intltool-m4-0.51.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:45 json-glib-1.4.4
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:43 ladspa-1.13
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:49 lame-3.100
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:52 libass-0.13.7
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:54 libcroco-0.6.12
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:53 libdca-0.0.5
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:51 libdv-1.0.0
drwxrwxr-x 11 ubuntu ubuntu      4096 12\uc6d4 13 00:28 libffi
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:31 libiconv-1.15
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:42 libjpeg-turbo-1.5.3
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:52 libkate-0.4.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:53 libmms-0.6.4
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:54 libnice-0.1.14
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:33 libogg-1.3.3
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:34 libpng-1.6.35
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:54 librsvg-2.40.20
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:53 librtmp-2.4_p20151223
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:48 libsoup-2.60.3
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:53 libsrtp-1.6.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:46 libtasn1-4.13
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:40 libtheora-1.1.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:14 libtool-2.4.6
drwxrwxr-x  5 ubuntu ubuntu      4096 12\uc6d4 13 01:43 libusrsctp
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:41 libvisual-0.4.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:39 libvorbis-1.3.6
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:51 libvpx-v1.7.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:33 libxml2-2.9.7
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:14 m4-1.4.18
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:17 meson-0.48.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:49 mpg123-1.25.10
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:45 nettle-3.4
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:17 ninja-1.8.2
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:44 opencore-amr-0.1.5
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:52 openh264-1.7.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:55 openjpeg-2.3.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:55 openssl-1.1.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:42 opus-1.3
drwxrwxr-x 10 ubuntu ubuntu      4096 12\uc6d4 13 00:42 orc
drwxrwxr-x 10 ubuntu ubuntu      4096 12\uc6d4 13 00:18 orc-tool
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:37 pango-1.42.4
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:34 pixman-0.34.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:17 pkg-config-0.29.2
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:31 proxy-libintl-0.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:43 sbc-1.3
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:54 soundtouch-2.1.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:42 spandsp-0.0.6
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:43 speex-1.2rc2
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:43 srt-1.3.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:50 taglib-1.11.1
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:44 tiff-4.0.9
drwxrwxr-x  6 ubuntu ubuntu      4096 12\uc6d4 13 00:43 tremor-1.2.1+r19427
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:18 vala-m4-0.35.2
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:54 vo-aacenc-0.1.3
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:50 wavpack-5.1.0
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:43 webrtc-audio-processing-0.2
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 01:45 x264-20161218-2245
drwxrwxr-x  2 ubuntu ubuntu      4096 12\uc6d4 13 00:28 zlib-1.2.11
```

**Comment by leemgs** [comment]
## How to run Android platform image on RPi3 board
* There two prebuilt images at community websites to save your time.
   *  Lineage OS - https://konstakang.com/devices/rpi3/
   *  Raspbian France community - https://raspbian-france.fr/download/and7_1-tablet-23012017.zip
* We recommend that you use an 'etcher' software to flash an Android platform image.
   * https://www.balena.io/etcher/
   * Screenshot (with microSD 64GiB):
      ![image](https://user-images.githubusercontent.com/82404/50620536-23d68e80-0f43-11e9-8b2c-0ab2c7b58bfb.png)

**Comment by leemgs** [comment]
How to deploy NNStreamer on Android software platform
======================================

When developers try to deploy their application based on NNstreamer library on Android software stack.
They need to understand the below three websites.  The related repositories are as following:

1. Building nnstreamer library (e.g., libnnstreamer.so) 
   * https://github.com/nnsuite/nnstreamer/tree/master/jni
2. How to run test application on real android device
   * https://github.com/nnsuite/nnstreamer-example/tree/master/android
3. How to add new CI module for an Android build test
   * https://github.com/nnsuite/TAOS-CI/pull/457

**Comment by myungjoo** [comment]
Released to the corredpondants.
